- .github/ISSUE_TEMPLATE/-issue-template.md
- .github/ISSUE_TEMPLATE/pull_request_template.md
- README.md
> PR 템플릿 만들기

- server/.eslintrc.js
> 서버 eslint setting

- android/app/build.gradle.kts
- android/app/src/main/res/drawable/home_tab_selector.xml
- android/app/src/main/res/drawable/ic_home.xml
- android/app/src/main/res/drawable/ic_home_filled.xml
- android/app/src/main/res/layout/activity_main.xml
- android/app/src/main/res/menu/bottom_navigation_items.xml
- android/app/src/main/res/navigation/catchytape_navigation.xml
- android/core/ui/build.gradle.kts
- android/core/ui/src/main/res/values/strings.xml
- android/feature/home/src/main/res/navigation/home_navigation.xml
- android/gradle/libs.versions.toml
- #48 
- bottom navigation 추가
- home tab 추가
> Navigation 설정

- android/core/ui/build.gradle.kts
- android/core/ui/src/main/java/com/ohdodok/catchytape/core/ui/BaseFragment.kt
> base fragment 생성

- android/core/ui/src/main/res/values/strings.xml
> 정해진 텍스트들 추가

- android/build-logic/build.gradle.kts
- android/build-logic/settings.gradle.kts
- android/build-logic/src/main/kotlin/gradle/plugin/AndroidFeaturePlugin.kt
- android/build-logic/src/main/kotlin/gradle/plugin/AndroidLibraryPlugin.kt
- android/core/data/build.gradle.kts
- android/core/ui/build.gradle.kts
- android/feature/home/build.gradle.kts
- android/gradle/libs.versions.toml
- android/settings.gradle.kts
- #66 
- build-logic 생성
- 안드로이드 모듈 필수 플러그인 생성
- feature 모듈 필수 플러그인 생성
> build-logic 플러그인 개발 

- android/build.gradle.kts
- android/core/data/build.gradle.kts
- android/core/data/src/main/java/com/ohdodok/catchytape/core/data/di/NetworkModule.kt
- android/gradle/libs.versions.toml
- #64 
-  retrofit 객체 생성할때, baseUrl 과 contentType은 일단 공백이랑 임의로 정해서 넣었습니다. 
- 서버가 정리되면, 추후에 변경해야 합니다.
- 멀티모듈 적용 후, build.gradle.kts 관리하는게 처음이라 어지럽네요 😂
- [역/직렬화 라이브러리 비교](https://github.com/boostcampwm2023/and04-catchy-tape/wiki/%EC%97%AD-%EC%A7%81%EB%A0%AC%ED%99%94-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EB%B9%84%EA%B5%90) wiki에 글을 썼습니다. 참고해주세요~
> Retrofit2 DI 및 직렬화 라이브러리 추가

- .github/workflows/android-pull-request-ci.yml
- #54 
- 안드로이드 폴더 내에 있는 파일 수정시 workflow가 트리거 된다.
원래 하나의 커밋이었는데 실험하다가 코드를 날려먹어서 복구 과정에서 커밋이 쪼개지게 됐어..!
https://algosketch.tistory.com/178
> 안드로이드 PR시 단위 테스트 자동화

- server/.dockerignore
- server/Dockerfile
- #126 
* 배포를 위한 dockerfile, dockerignore 작성
> Dockerfile 작성

- server/src/entity/music_playlist.entity.ts
- server/src/playlist/playlist.service.ts
- server/src/upload/upload.controller.ts
- server/src/upload/upload.service.ts
- server/src/user/user.controller.spec.ts
- server/src/user/user.controller.ts
- server/src/user/user.module.ts
- server/src/user/user.service.spec.ts
- server/src/user/user.service.ts
- #62 
* `/users/recent-played` API
* User 모듈에 Music_Playlist, Playlist, Music 관련 의존성 추가
* Music_Playlist의 엔티티에서 최근 재생한 음악 10개 가져옴
빼먹은 타입 표시, 이상한 로직 체크 부탁 드립니다!
> 홈화면에서 사용자가 최근 재생한 음악 가져오기 

- server/src/music/music.controller.ts
- server/src/music/music.service.ts
- #155 
* user 정보 추가 (userId, nickname)
> 최근 업로드 된 음악 목록에 user 정보 추가

- android/feature/home/src/main/java/com/ohdodok/catchytape/feature/home/HomeFragment.kt
- android/feature/player/src/main/res/navigation/player_navigation.xml
- #6 
- 충돌 날 것 같아, develop 에서 branch 파서 개발하였습니다.
- 간단한 기능이라, 코드 변화랑이 별로 없습니다
> 최근 재생한 노래 클릭시, Home -> Player 화면 이동

- android/core/data/src/main/java/com/ohdodok/catchytape/core/data/di/ApiModule.kt
- android/core/data/src/main/java/com/ohdodok/catchytape/core/data/di/RepositoryModule.kt
> 싱글톤 어노테이션, Retrofit Service 생성 간소화

- server/src/auth/auth.service.ts
- server/src/auth/jwt.strategy.ts
- server/src/dto/musicCreate.dto.ts
- server/src/entity/music.entity.ts
- server/src/entity/music_playlist.entity.ts
- server/src/music/music.controller.ts
- server/src/music/music.service.ts
- server/src/playlist/playlist.controller.ts
- server/src/playlist/playlist.service.ts
- server/src/upload/upload.controller.ts
- #184 
- music 테이블의 musicId 를 music_id 로 수정
- music_id 필드에 uuid 를 넣기위해 music_id 필드를 string 타입으로 수정
> music 필드명 수정

- server/src/upload/upload.controller.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
- #58 
- `PATCH` `/users/image` 로 프로필 사진 수정
- 완료 응답으로 user_id 반환
- 프로필 사진 수정 테스트
> 사용자 프로필 이미지 수정 API 구현

- server/src/upload/upload.controller.ts
> uploadMusic, uploadImage 복구

- server/src/constants.ts
- server/src/upload/upload.service.ts
- #124 
* 이미지: image/png, 음악: audio/mpeg
정말 간단히 Content-Type만 추가했슴다!
> 업로드 url에 content-type추가

- server/src/music/music.service.ts
- server/src/upload/upload.service.ts
- #201 
* path.resolve 경로 출돌 수정
* upload시 read 권한 설정
> 파일 업로드 권한 수정, 경로 수정

- .github/workflows/server-cd.yml
- server/src/auth/auth.module.ts
> JWT 유효기한 변경

- server/src/music/music.controller.ts
- server/src/music/music.service.ts
- #206 
- **`GET` `/musics/info?music_id={음악 ID}`**
- 테스트
- 실패 테스트
> 음악 정보 불러오기 API 구현

- android/app/src/main/res/layout/activity_main.xml
- android/core/ui/src/main/res/values/strings.xml
- android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerControlView.kt
- android/feature/player/src/main/res/layout/view_player_bar.xml
- android/feature/player/src/main/res/layout/view_player_control.xml
- android/feature/player/src/main/res/values/attrs.xml
- android/feature/player/src/main/res/values/strings.xml
- #174 
- 바텀 재생바를 이용할 수 있는 커스텀 뷰 구현
> 바텀 재생 바 UI 구성

- server/src/dto/playlistCreate.dto.ts
- #210 
- 플레이리스트 제목이 숫자가 안되는 이슈 발견, 조치
> 플레이리스트 제목 숫자 추가

- server/src/entity/music_playlist.entity.ts
- server/src/entity/playlist.entity.ts
- server/src/playlist/playlist.service.ts
- #153 
playlist 필드명 변경 (playlist_Id -> playlist_id)
> playlist_id 필드명 변경

- server/src/dto/playlistCreate.dto.ts
> 플레이리스트 제목 제한 수정

- server/src/music/music.service.ts
- #124 
* 원래는 presigned url을 받았던 자리이나, 현재는 로직이 변해 사용되지 않음
> music DB에 저장 시 불필요한 코드 제거

- android/app/build.gradle.kts
- android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
- android/app/src/main/res/layout/activity_main.xml
- android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerControlView.kt
- android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerFragment.kt
- android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerViewModel.kt
- android/feature/player/src/main/res/layout/view_player_control.xml
- #175 
- `activityViewModel()` 로 Player 상태를 공유 하였습니다.
- 이전, 다음곡 기능이 완성 되면 바텀 바에도 넣을 생각입니다~
> Bottom Player 동작 구현

- server/src/music/music.service.ts
- server/src/upload/upload.service.ts
- #242 
- try catch 추가, 에러코드 구체화
> uploadEncodedFile 에외처리 추가

- server/src/dto/musicCreate.dto.ts
> 음악 제목 숫자 추가

- android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/usecase/upload/ValidateMusicTitleUseCase.kt
- android/core/domain/src/test/java/com/ohdodok/catchytape/core/domain/usecase/signup/MusicTitleValidationUseCaseTest.kt
- android/core/domain/src/test/java/com/ohdodok/catchytape/core/domain/usecase/upload/MusicTitleValidationUseCaseTest.kt
- android/feature/upload/src/main/java/com/ohdodok/catchytape/feature/upload/UploadFragment.kt
- android/feature/upload/src/main/java/com/ohdodok/catchytape/feature/upload/UploadViewModel.kt
- android/feature/upload/src/main/res/layout/fragment_upload.xml
- android/feature/upload/src/main/res/values/strings.xml
- #241 
- 업로드 음악 제목 유효성 검사
- 테스트 코드 작성
> 업로드 음악 제목 유효성 검사

- android/app/build.gradle.kts
- android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
- android/app/src/main/res/layout/activity_main.xml
- android/core/data/src/main/java/com/ohdodok/catchytape/core/data/api/UserApi.kt
- android/core/data/src/main/java/com/ohdodok/catchytape/core/data/repository/PlaylistRepositoryImpl.kt
- android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/repository/PlaylistRepository.kt
- android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerFragment.kt
- android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerViewModel.kt
- #245 
- 최근 재생한 노래가 있을 때만 bottom player 가 보이게 합니다.
- player 기능에는 네트워크 에러 처리가 안되어 있어서  추가적으로 진행했습니다.
> 최근 재생한 노래가 있을 때 bottom player 보이기

- android/feature/home/src/main/java/com/ohdodok/catchytape/feature/home/HomeFragment.kt
- android/feature/home/src/main/java/com/ohdodok/catchytape/feature/home/HomeViewModel.kt
- android/feature/home/src/main/res/layout/fragment_home.xml
- android/feature/playlist/src/main/res/layout/fragment_playlist_detail.xml
- #302
- 홈화면에서 최근 재생한노래 누르면 최근재생한목록 재생 시작!
> 최근 재생한 노래 재생

- server/package-lock.json
- server/package.json
- server/src/config/ncloud.config.ts
- #293 
이게 맞을 진 모르겠는데 일단 모듈 설치했어요..!
> @types/crypto-js 모듈 추가

- android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
- android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerFragment.kt
- android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerViewModel.kt
> 껐다 켜면 자동 재생하는 문제

- server/src/config/ncloud.config.ts
- #293
CryptoJS 모듈 자체를 들고 와서 문제가 있나 싶어서 안의 함수만 import 해왔어요!
> Crypto 모듈 사용 부분 코드 수정

- .github/workflows/server-cd.yml
> fix : 잘못된 secret key 설정 수정

- server/src/app.controller.spec.ts
- server/src/app.service.ts
- server/test/app.e2e-spec.ts
- #293 
- github actions 트리거용 수정
> github actions 트리거용 수정

- android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/model/CtErrorType.kt
- android/core/ui/src/main/java/com/ohdodok/catchytape/core/ui/cterror/CtError.kt
- android/core/ui/src/main/res/values/strings.xml
- android/feature/home/src/main/java/com/ohdodok/catchytape/feature/home/HomeFragment.kt
- android/feature/login/src/main/java/com/ohdodok/catchytape/feature/login/LoginFragment.kt
- android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyMusicsFragment.kt
- android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyPageFragment.kt
- android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerFragment.kt
- android/feature/playlist/src/main/java/com/ohdodok/catchytape/feature/playlist/PlaylistDetailFragment.kt
- android/feature/playlist/src/main/java/com/ohdodok/catchytape/feature/playlist/PlaylistsFragment.kt
- android/feature/search/src/main/java/com/ohdodok/catchytape/feature/search/SearchFragment.kt
- android/feature/upload/src/main/java/com/ohdodok/catchytape/feature/upload/UploadFragment.kt
- android/feature/upload/src/main/java/com/ohdodok/catchytape/feature/upload/UploadViewModel.kt
- #220 
- 음원 업로드시 인코딩하는 로직으로 변경
- 유해 이미지 및, 인코딩 에러 관련 코드 추가
- 에러 string 값 수정
> 업로드 과정 중 예외 처리

- .github/workflows/server-cd.yml
- #319 
- 도커 볼륨 마운트를 이용해서 컨테이너 서버의 로그파일 경로를 호스트 시스템 경로에 마운트
- 로컬 테스트 -> 컨테이너의 로그파일이 호스트 시스템에 잘 저장되는 것 확인
> 서버 로그 파일 저장 경로 설정

- android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyPageFragment.kt
- #322 
단순 listener 추가라, 코드량이 적습니다~
> 마이 페이지에서 업로드 화면으로 이동

- server/src/music/music.controller.spec.ts
- server/test/constants/music.mockData.ts
- #318 
- test DB안에 담긴 임시 사용자를 auth를 모킹하여 반환하도록 하였습니다...
몇자 작성하진 않았어요!
> Music e2e 테스트 추가

- android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
- #344 
- 네비게이션 애니메이션 동작 중첩시 안되는 버그 해결
[참고 공식 문서](https://developer.android.com/develop/ui/views/animations/reveal-or-hide-view?hl=ko)
> 네비게이션 애니메이션 동작

- android/build-logic/build.gradle.kts
- android/core/data/build.gradle.kts
- android/core/domain/build.gradle.kts
- android/core/ui/build.gradle.kts
- android/feature/home/build.gradle.kts
- android/feature/login/build.gradle.kts
- android/feature/mypage/build.gradle.kts
- android/feature/player/build.gradle.kts
- android/feature/playlist/build.gradle.kts
- android/feature/search/build.gradle.kts
- android/feature/upload/build.gradle.kts
- #347 
- gradle kotlin options 추출
> gradle kotlin options 추출

- server/src/entity/recent_played.entity.ts
- server/src/entity/user.entity.ts
- server/src/music/music.service.ts
- server/src/user/user.controller.spec.ts
- server/src/user/user.service.spec.ts
- server/src/user/user.service.ts
- #361 
- update 부분의 트랜잭션 구현
- updateRecentPlayed 테스트 - DB에 적용되는 것도 확인 완료
> music, user 트랜잭션

- .github/workflows/server-cd.yml
- server/src/music/music.repository.ts
> redis 관련 CD 파일 수정

- server/src/auth/auth.controller.ts
- server/src/auth/auth.service.ts
- #383
- `/users/signup`의 반환값에 refreshToken도 추가합니다.
> /users/signup 반환값 수정

- .github/workflows/server-cd.yml
- server/deploy.sh
- #397 
* blue green 방식 동작으로 설정
> 무중단배포 쉡 스크립트 작성

- server/deploy.sh
* 변경할 포트번호 수정
* [디버깅 과정](https://round-caution-9fd.notion.site/9e409f0304874583b1b4560913b23020?pvs=4)
> deploy.sh 수정

- server/nest/src/auth/auth.service.ts
> refresh token 내용 수정

- server/nest/src/auth/auth.controller.ts
- server/nest/src/auth/auth.service.ts
- server/nest/src/repository/playlist.repository.ts
- server/nest/src/user/user.controller.ts
- server/nest/src/user/user.service.ts
- #416
- `BAD_REQUEST` -> `SERVER_ERROR`로 수정
(서버 네트워크 등의 문제로 발생한 에러가 잘못된 요청 상태 코드로 표시되고 있었음)
- DELETE `/users` user 모듈로 옮김
별건 아니라서 한번 보시고 어푸룹 해주심 될 것 같아용!
> Service 계층에서 발생하는 에러 상태 코드 수정
