android/app/build.gradle.kts
android/app/src/main/java/com/ohdodok/catchytape/CtApplication.kt
android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
android/app/src/main/res/values/strings.xml
android/gradle/libs.versions.toml

- #75 
- `override fun createStackElementTag` 을 통해 추후에 커스텀 가능
- git pull 하시고, gradle sync 했는데도, `BuildConfig` 인식 안되면, 스튜디오에서 clean and rebuild project 하시면 됩니다

timber 적용

---

.github/workflows/android-pull-request-ci.yml
android/.gitignore
android/app/build.gradle.kts

- #89 
- 디버그 사이닝 키스토어를 공유할 수 있다.
- GitHub Actions settings에 debug.keystore 및 keystore.properties 추가
- workflow에서 해당 변수를 가져오도록 설정
- 빌드시 build.gradle에 명시된 keystore를 통해 사이닝

keystore 공유를 위한 설정

---

android/app/src/main/res/values/strings.xml
android/build-logic/src/main/kotlin/gradle/plugin/AndroidFeaturePlugin.kt
android/build-logic/src/main/kotlin/gradle/plugin/AndroidLibraryPlugin.kt
android/core/data/build.gradle.kts
android/core/data/src/main/java/com/ohdodok/catchytape/core/data/di/NetworkModule.kt
android/gradle/libs.versions.toml

- #75 
https://github.com/boostcampwm2023/and04-catchy-tape/pull/76#issuecomment-1810203177
- httpLoggingInterceptor 에서 따로 처리를 해야만, release build 시에 Log 가 출력 안되는 걸로 확인되었습니다.
- 코멘트 주신대로 그 부분 처리했습니다.
- `timber_log_format` 도 약간 수정했습니다 ('/' 가 있으면 좀 다르게 출력되어 뺐습니다.)

build type에 따른 httpinterceptor Logging

---

.github/workflows/android-pull-request-ci.yml
android/build-logic/src/main/kotlin/gradle/plugin/AndroidFeaturePlugin.kt
android/build.gradle.kts
android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/repository/UserRepository.kt
android/core/ui/src/main/java/com/ohdodok/catchytape/core/ui/BaseFragment.kt
android/feature/login/build.gradle.kts
android/feature/login/src/main/java/com/ohdodok/catchytape/feature/login/LoginFragment.kt
android/feature/login/src/main/java/com/ohdodok/catchytape/feature/login/LoginViewModel.kt
android/gradle/libs.versions.toml

- #90 
- Google token 가져오기 [공식 문서](https://android-developers.googleblog.com/2016/03/registering-oauth-clients-for-google.html)
- google server client id 는 local.properties 에 저장 시켜서 가져옵니다
서버를 기다리는 중이라 google token 받아오는 코드만 우선 pr 올립니다~
google server client id 는 따로 드릴게여

구글 로그인 - google token 가져오기

---

.github/workflows/android-cd.yml
android/app/build.gradle.kts

- #87 
- release apk 에 서명 포함    [공식문서](https://developer.android.com/build/building-cmdline)
- 태그를 푸쉬하면,  apk 파일을 빌드하고 apk 파일을 release하는 워크플로우 구축
개인 레포에서 테스트 한 Screenshot  입니당

Android Release APK 배포 자동화

---

.github/workflows/server-dev-ci.yml
server/package.json
server/src/auth/auth.controller.spec.ts
server/src/auth/auth.service.spec.ts
server/src/user/user.controller.spec.ts
server/src/user/user.service.spec.ts

- #114 
* 환경 변수는 사용되면 추후 추가 예정 (DB, NCP 인증키)
* (다만 안드처럼 단위 테스트는 아니라서 너무 단순한가 싶기도 하네요!)
(제 개인 레포에서는 잘 돌아가서 첨부해놓습니당!)
노션에 전체적인 흐름 간단하게 적어놨는데 코드 자체가 직관적이라서! 추가하고 싶은 부분 있음 말씀해주세요!

서버 테스트 자동화 코드 작성

---

.github/workflows/android-cd.yml
android/app/build.gradle.kts

- #119
- apk 파일 Firebase 에 배포 자동화
https://github.com/marketplace/actions/firebase-app-distribution
개인 레포에서 테스트 후 스크린샷 입니당

Android Firbase App 배포 자동화

---

server/src/auth/auth.controller.ts
server/src/auth/auth.service.ts

- #132 
* `GET` `/users/verify` 로 사용자 검증. (헤더에 JWT 토큰 필요)
-> 성공시 200, userId 응답
* `DELETE` `/users` 로 사용자 탈퇴. (헤더에 JWT 토큰 필요)
-> 성공시 200, userId 응답
- 검증  API
- 탈퇴 API

사용자 검증 API, 탈퇴 API 구현

---

.github/workflows/android-pull-request-ci.yml
android/build.gradle.kts
android/core/domain/build.gradle.kts
android/core/domain/src/test/java/com/ohdodok/catchytape/core/domain/KoTestConfig.kt
android/core/domain/src/test/java/com/ohdodok/catchytape/core/domain/SampleTest.kt
android/core/domain/src/test/java/com/ohdodok/catchytape/core/domain/signup/TestConfig.kt

- #118 
- Kotest에서도 단위 테스트 보고서를 업로드하도록 설정
- TestConfig path를 적절한 경로로 변경
- project 수준의 build.gradle.kts이 아닌 모듈에다가 task를 설정했어야 했다.
- testDebugUnitTest 로는 Domain 모듈을 인식 할 수 없으므로, root gradle에 domain:test 하는 Task 추가

Kotest CI result 업로드

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
android/app/src/main/java/com/ohdodok/catchytape/NetworkStateObserver.kt
android/core/ui/src/main/res/values/strings.xml

- #110 
다음 시나리오에서 "네트워크 연결을 확인해 주세요."라는 토스트를 띄운다.
- 앱에 진입했는데, 네트워크 연결이 안 되어 있을 경우
- 특정 네트워크를 잃었는데, 더 이상 연결 가능한 네트워크가 없을 경우
시나리오는 유튜브 뮤직을 테스트 해봤어

네트워크 연결 상태 확인

---

server/package-lock.json
server/package.json
server/src/config/ncloud.config.ts
server/src/constants.ts
server/src/upload/upload.controller.ts
server/src/upload/upload.module.ts
server/src/upload/upload.service.ts

- #124 
- 클라이언트가 `/upload?path=아래 세 개의 경로 중 하나형태&fileName=파일이름&ext=확장자` 로 요청(GET)
=> Presigned URL 반환
=> 이후 URL에 **PUT** 요청(binary 형태의 file)을 보내면 업로드 성공!
** 바뀐 로직
1. 업로드 화면으로 들어갈 때 서버에 한 번 요청을 보냄 → 서버는 uuid 값을 반환
2-1. 클라에서 음악 업로드를 하고 싶으면 {type: music, uuid: uuid} 로 요청을 보냄 → 서버에서 /music/{uuid}/music.mp3 의 presigned url 을 응답 → 클라이언트에서 해당 url 로 음악 업로드
2-2. 음악 cover(사진) 업로드를 하고 싶으면 {type: cover, uuid: uuid} 로 요청을 보냄 → 서버에서 /image/cover/{uuid}/cover.png 의 presigned url 응답 → 클라이언트에서 해당 url 로 커버 사진 업로드
- 다만 문제가 많습니다 🥲 (코드를 짜는게 아니라 생각하느라 오래 걸린 것 같네요ㅠㅠ)
1. 버킷 비공개 전환 시 추가해야 하는 인증 헤더 코드가 잘 작동되지 않아 현재 **버킷은 매우 public한 상태**
2.  같은 경로의 중복된 이름은 최근 파일로 덮어씌워집니다....
- 음악/이미지 업로드
- 잘못된 uuid 입력 시
- user 정보 없을 시

Presigned URL 활용한 업로드

---

server/src/upload/upload.module.ts
server/src/upload/upload.service.ts

- #124 
- 서버 CD가 이루어질 때 업로드 관련 Pull Request에서 미처 빼지 못한 모듈이 있어 문제가 발생하여 이를 제거
- uuid 형태의 string만 넘겨받기

업로드 관련 버그 수정

---

server/src/entity/music_playlist.entity.ts
server/src/entity/playlist.entity.ts
server/src/playlist/playlist.controller.ts
server/src/playlist/playlist.service.ts

- #36 
- **`GET` `/playlists` 플레이리스트 조회**
- **`GET` `/playlists/{playlistId}` 플레이리스트에 들어있는 음악 조회**
- 응답은 Swagger 참고
- 플레이리스트에 이미 추가된 음악을 추가 요청했을 때 `400` `ALREADY_ADDED` 응답
- **`GET` `/playlists` 플레이리스트 조회**
- **플레이리스트에 이미 추가된 음악을 추가 요청했을 때**
- **`GET` `/playlists/{playlistId}` 플레이리스트에 들어있는 음악 조회**
service 에서 DB 에 접근하는 로직이 길어져서 가독성을 망친다고 생각해 **Active Record 패턴**을 적용해서 Entity 내에 DB 접근 로직을 넣었습니다. service 계층에서 조금이라도 가독성이 망가진다면 **Active Record 패턴**을 적극적으로 사용하는 것이 좋을 것 같다고 생각합니다!
[참고자료](https://imsoncod.tistory.com/m/40)

플레이리스트 조회 API

---

server/src/entity/music.entity.ts
server/src/music/music.controller.ts
server/src/music/music.service.ts

- #158 
- **`GET` `/musics/my-uploads?cound={개수}` 로 내가 업로드한 음악 요청**
- API 재사용 가능성을 고려하여 query 로 count 를 지정하도록 했습니다.
- **테스트 사진 (음악이 1개밖에 없는 상태)**

홈 화면 노래 요청 (내가 업로드한 노래)

---

android/core/data/src/main/java/com/ohdodok/catchytape/core/data/api/MusicApi.kt
android/core/data/src/main/java/com/ohdodok/catchytape/core/data/di/NetworkModule.kt
android/core/data/src/main/java/com/ohdodok/catchytape/core/data/model/MusicResponse.kt
android/core/data/src/main/java/com/ohdodok/catchytape/core/data/model/MusicsResponse.kt
android/core/data/src/main/java/com/ohdodok/catchytape/core/data/model/NicknameResponse.kt
android/core/data/src/main/java/com/ohdodok/catchytape/core/data/repository/MusicRepositoryImpl.kt
android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/model/Music.kt
android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/repository/MusicRepository.kt
android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/usecase/GetRecentUploadedMusic.kt
android/core/ui/src/main/res/layout/item_music_horizontal.xml
android/core/ui/src/main/res/layout/item_music_vertical.xml
android/feature/home/src/main/java/com/ohdodok/catchytape/feature/home/HomeViewModel.kt
android/feature/home/src/main/res/layout/fragment_home.xml

- #9 
- 최근 업로드된 노래 서버에서 가져오기 (아티스트명 임시입니당)
- ignoreUnknownKeys 추가 [공식문서](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/-json-builder/ignore-unknown-keys.html)
default 값이 false 여서 true 로 바꿔줌! 안해주면 사용하지 않는 키를 무시하지 않고 에러가 발생함
- 홈화면에 NestedScrollView 추가!

최근 업로드된 노래

---

server/src/user/user.controller.ts
server/src/user/user.service.ts

- #7 
- 내 정보를 응답하는 API 구현
- `GET` `/users/my-info` 로 요청
- user_id, nickname, photo, user_email, created_at 응답

사용자 정보 불러오기

---

server/src/entity/music_playlist.entity.ts
server/src/music/music.controller.ts
server/src/playlist/playlist.service.ts

- #215 
- 플레이리스트 API 응답에 음악 개수, 썸네일 링크를 추가했습니다.
<br>
- playlist id 로 음악의 개수, 썸네일을 반환하는 함수들을 추가하여 처리했습니다.
- 특성상 쿼리문이 많이 발생하게 되어서 Promise.all 로 병렬 처리를 시켜서 시간을 단축시켰습니다.
- 테스트 (11ms)
참고자료 - [[JS] forEach 함수는 async 함수를 기다려주지 않는다](https://constructionsite.tistory.com/43)
쿼리문들을 병렬 처리시켜서 시간을 단축하기는 했지만, 쿼리문이 많이 발생하는 것이 사실이라 근본적으로 줄일 수 있다면 줄이는 것이 좋아 보입니다.

플레이리스트 정보에 음악 개수, 썸네일 링크 추가

---

server/src/music/music.service.ts
server/src/upload/upload.service.ts

- #124
* 기존의 파일명은 한글로 들어가면 인코딩 문제로 골치를 앓아서, 경로가 이미 music과 user id로 구분되기 때문에 파일명은 고정시켰다.
* music.mp3, image.png로 고정

업로드 시 파일명 고정

---

android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerControlView.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerFragment.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerListener.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerViewModel.kt
android/feature/player/src/main/res/layout/view_player_control.xml
android/feature/player/src/main/res/values/strings.xml
android/feature/playlist/src/main/java/com/ohdodok/catchytape/feature/playlist/PlaylistsFragment.kt
android/feature/playlist/src/main/res/navigation/playlist_navigation.xml

- #12 
- Bottom Player, PlayerFragment 2개에서 모두 이전, 다음 노래 이동 기능을 구현하였습니다.
- 현재 m3u8 파일은 dummys 데이터로 하드 코딩 하였고, 이후에 이 코드는 삭제 필요합니다.
- 현재 Issue 외에, 네이밍 개선과 불필요한 코드를 제거 하였습니다. (처음 3개의 커밋)

이전, 다음 노래 이동 

---

android/app/src/main/res/layout/activity_main.xml
android/core/ui/src/main/res/color/navigation_view_item_icon_tint.xml
android/core/ui/src/main/res/values-night/themes.xml
android/core/ui/src/main/res/values/themes.xml

- #254 
- 바텀 내비게이션 색깔 변경
- 나중에 테마 정리가 필요할 것 같아
- 머티리얼 컴포넌트에서 secondary쪽 색깔까지 사용하는 것 같아서, 이번에 변경하면서 테마에 값 하나 지정해줬어.
- activeIndicator가 colorSecondaryContainer를 찾아서 적용하고 있어

바텀 내비게이션 스타일

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
android/app/src/main/java/com/ohdodok/catchytape/mediasession/PlaybackService.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerFragment.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerUtil.kt

- #122 
- Player에 대한 기능에서, MainActivity와 PlayerFragment 공통으로 사용하는 로직을 PlayerUtil.kt 파일에 확장함수로 작성하였습니다.
- MediaMetadata 을 설정해야, Media Control에 제대로 배경과, title 정보가 나타나게 됩니다. 
- android api 33 이전 버전에도 MediaMetadata 설정을 해야 UI가 표시됩니다. 
스크린샷은 Android api 33에서 찍었습니다.

MediaSession 을 이용한 Media Control Player UI

---

android/core/data/src/main/java/com/ohdodok/catchytape/core/data/api/MusicApi.kt
android/core/data/src/main/java/com/ohdodok/catchytape/core/data/model/MusicResponse.kt
android/core/data/src/main/java/com/ohdodok/catchytape/core/data/repository/MusicRepositoryImpl.kt
android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/repository/MusicRepository.kt
android/feature/search/src/main/java/com/ohdodok/catchytape/feature/search/SearchFragment.kt
android/feature/search/src/main/java/com/ohdodok/catchytape/feature/search/SearchViewModel.kt
android/feature/search/src/main/res/layout/fragment_search.xml

- #256
- 스크린샷.gif 에서만 더보기 전에는 '2'개가 보이고, 더보기 클릭시 모두 표시하게 하였습니다 (코드 상에서는 3개를 표시해요)
- #239, PR merge 후에 노래 클릭시 player 화면으로 이동을 구현할 예정

노래 검색 및 더보기 기능

---

server/src/auth/auth.controller.spec.ts
server/src/auth/auth.module.ts
server/src/auth/auth.service.spec.ts
server/src/auth/auth.service.ts
server/src/constants.ts
server/src/entity/music.entity.ts
server/src/entity/music_playlist.entity.ts
server/src/entity/recent_played.entity.ts
server/src/entity/user.entity.ts
server/src/music/music.controller.spec.ts
server/src/music/music.service.spec.ts
server/src/playlist/playlist.controller.ts
server/src/playlist/playlist.module.ts
server/src/playlist/playlist.service.ts
server/src/user/user.controller.spec.ts
server/src/user/user.controller.ts
server/src/user/user.module.ts
server/src/user/user.service.spec.ts
server/src/user/user.service.ts
server/test/constants/music.mockData.ts

- #287 
- Recent_Played 테이블 생성
- Music_Playlist 테이블 updated_at -> created_at 으로 필드명 변경
- 모든 최근 재생 목록 관련 API들 User 모듈로 이동
- `/user/recent-played` `PATCH` -> `PUT`
- `GET` `/user/recent-info` 음악 수, 썸네일 링크 응답하는 API 구현
- 불필요한 모듈 의존 관계 삭제
- `GET` `/users/recent-info` 최근 재생 목록 정보 API
- `GET` `/users/recent-played` 최근 재생 목록 노래 정보 API
- `PUT` `/users/recent-played` 최근 재생 목록 노래 update

Recent_Played 테이블 생성 + API 수정

---

android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
android/core/ui/src/main/java/com/ohdodok/catchytape/core/ui/RootViewInsetsCallback.kt
android/feature/home/src/main/java/com/ohdodok/catchytape/feature/home/HomeFragment.kt
android/feature/home/src/main/res/layout/fragment_home.xml
android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyMusicsFragment.kt
android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyPageFragment.kt
android/feature/mypage/src/main/res/layout/fragment_my_musics.xml
android/feature/mypage/src/main/res/layout/fragment_my_page.xml
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerFragment.kt
android/feature/player/src/main/res/layout/fragment_player.xml
android/feature/playlist/src/main/java/com/ohdodok/catchytape/feature/playlist/PlaylistsFragment.kt
android/feature/playlist/src/main/res/layout/fragment_playlists.xml
android/feature/search/src/main/java/com/ohdodok/catchytape/feature/search/SearchFragment.kt
android/feature/search/src/main/res/layout/fragment_search.xml
android/feature/upload/src/main/java/com/ohdodok/catchytape/feature/upload/UploadFragment.kt
android/feature/upload/src/main/res/layout/fragment_upload.xml

- #289
키보드가 보일 때, 화면이 보이지 않는 이슈 해결
스크린 영역을 확장하면서 activity의 fitsSystemWindow를 false 로 설정해줬었음.
fitsSystemWindow 가 true 면 system window의 padding 이 적용되는데, false 를 하면 padding이 적용되지 않음.
fitsSystemWindows="true" 설정하면 기본 값 insets를 적용하면서 시스템 영역(상태바, 네비게이션 바)를 가리지 않게 해줌.
확장 스크린을 쓰지 않는 뷰에서는 rootview 에 android:fitsSystemWindows="true" 를 설정해었는데 
상태바, 네비게이션 바 의 패딩 값을 주게되어 불필요한 네비게이션 바의 패딩을 가지게 됌.
뿐만아니라 fitsSystemWindows="true" 면 키보드가 올라올 때 키보드 높이만큼 공간을 차지하게 됌
그래서 view 에 [OnApplyWindowInsetsListener](https://developer.android.com/reference/android/support/v4/view/OnApplyWindowInsetsListener?hl=ko) 를 적용하여 뷰의 패딩을 업데이트 해줌.
[참고블로그](https://sungbin.land/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-windowinsets%EC%9C%BC%EB%A1%9C-%ED%82%A4%EB%B3%B4%EB%93%9C-%EC%95%A0%EB%8B%88%EB%A9%94%EC%9D%B4%EC%85%98-%EA%B5% …

키보드가 보일 때, 화면이 보이지 않는 이슈 해결

---

server/Dockerfile
server/src/entity/music.entity.ts
server/src/entity/music_playlist.entity.ts
server/src/entity/playlist.entity.ts
server/src/entity/recent_played.entity.ts
server/src/user/user.service.ts

- #288 
- 정했던 컬럼에 대해서 인덱스 추가
- 도커 컨테이너 타임존 서울로 변경
- 인덱스
- 컨테이너 시간

DB 인덱스 추가 + 도커 컨테이너 타임존 설정

---

android/app/src/main/java/com/ohdodok/catchytape/mediasession/PlaybackService.kt

- #123 
- 앱이 완전히 종료되면 Service를 종료시킨다.
- 무음 모드에서는 전화가 와도 계속 재생 됨
- 소리 모드에서는 전화가 오면 전화 벨소리가 들리고, 음악을 중지 됨

백그라운드에서 노래 재생 관리

---

android/feature/playlist/src/main/java/com/ohdodok/catchytape/feature/playlist/PlaylistsFragment.kt
android/feature/playlist/src/main/java/com/ohdodok/catchytape/feature/playlist/PlaylistsViewModel.kt
android/feature/playlist/src/main/res/layout/fragment_playlists.xml

- #326 
- 클래스 이름과 파일 이름이 불일치하여 리팩토링 PlaylistViewModel -> PlaylistsViewModel
- 재생 목록 추가 후 다시 fetch

재생 목록 추가시 UI 즉시 반영

---

android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
android/core/ui/src/main/java/com/ohdodok/catchytape/core/ui/PlaylistBottomSheet.kt
android/core/ui/src/main/java/com/ohdodok/catchytape/core/ui/PlaylistBottomSheetViewModel.kt
android/core/ui/src/main/res/values/strings.xml

- #298 
- Fragment를 띄우면 하단 재생 바가 자기 부른 줄 알고 같이 올라옴 (해결)
- 예외 처리(이미 추가된 노래일 경우 등)가 안 되어 있음 (해결)
- 정상적으로 추가되면 알림 메시지를 띄워줘야 함 (해결)
- 이유는 모르겠으나 바텀 시트가 떠 있는 동안 재생 버튼이 사라짐 (미결)
- UI radius 추가하거나 디자인을 바꿔야 함 (미결)
- 사진 썸네일이 짤리는 현상 (미결)
중요한 이슈 먼저 해결했어

음악을 재생목록에 추가할 때 발생하는 이슈 처리

---

android/app/src/main/java/com/ohdodok/catchytape/mediasession/PlaybackService.kt
android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/usecase/player/CurrentPlayListUseCase.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerViewModel.kt
android/gradle/libs.versions.toml

- #329 
- Android Api 33, emulator 에서 버그 제거
- coroutine 버전 변경

앱 재진입시 재생 버그 fix (재생 중(isPlaying=true)인 상태에서 앱 종료)

---

android/app/build.gradle.kts
android/app/src/main/java/com/ohdodok/catchytape/MainActivity.kt
android/build-logic/src/main/kotlin/gradle/plugin/AndroidFeaturePlugin.kt
android/core/ui/src/main/res/values/strings.xml
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerFragment.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerViewModel.kt

네트워크가 없는 상태에서, 이전 곡, 다음 곡 이동 예외 처리

---

android/app/src/main/AndroidManifest.xml
android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/utils/CoroutineUtils.kt
android/core/ui/src/main/java/com/ohdodok/catchytape/core/ui/BaseFragment.kt
android/core/ui/src/main/java/com/ohdodok/catchytape/core/ui/ViewUtils.kt
android/core/ui/src/main/res/layout/bottom_sheet_playlist.xml
android/feature/home/src/main/java/com/ohdodok/catchytape/feature/home/HomeFragment.kt
android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyMusicsFragment.kt
android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyMusicsViewModel.kt
android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyPageFragment.kt
android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyPageViewModel.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerFragment.kt
android/feature/player/src/main/java/com/ohdodok/catchytape/feature/player/PlayerViewModel.kt
android/feature/playlist/src/main/java/com/ohdodok/catchytape/feature/playlist/PlaylistDetailFragment.kt
android/feature/playlist/src/main/java/com/ohdodok/catchytape/feature/playlist/PlaylistsFragment.kt
android/feature/search/src/main/java/com/ohdodok/catchytape/feature/search/SearchFragment.kt
android/feature/upload/src/main/res/layout/fragment_upload.xml

- #338 
- #340
- 플레이리스트 추가 bottom 짤리는 ui
- Player에서 ‘저장’ 빠르게 두번 누르면, 앱 터짐
- throttleFirst 사용 
- 화면 회전 금지
- MyPage, MyMusics에서 노래 클릭시 해당 곡의 Player로 이동
- 새 재생목록 추가 버튼 클릭 throttleFist 처리

QA에서 발견한 버그 개선 및 MyPage -> Player 이동

---

android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/model/CtErrorType.kt
android/core/ui/src/main/java/com/ohdodok/catchytape/core/ui/cterror/CtError.kt
android/core/ui/src/main/res/values/strings.xml

- #341 
- 음악 object storage 업로드 중 오류 코드 추가

음악 업로드 에러 추가

---

server/src/playlist/playlist.controller.ts
server/src/playlist/playlist.service.ts

- #366 
* DB에서 해당 playlist 부분 삭제
* DB에서 music_playlist 테이블에 있는 레코드 중 해당 playlist에 담긴 음악 부분 모두 삭제
* 트랜잭션 추가 (중간에 Error 터졌을 때 롤백 되는 것을 확인)
* 정상적으로 동작할 때 DB에 playlist 테이블에서 해당 플레이리스트가 삭제되고, music_playlist 테이블에서 해당 플레이리스트의 음악 행들이 삭제됨을 확인
- 삭제 할 플레이리스트와, 그 안에 담긴 음악 정보
- 삭제가 정상적으로 이뤄졌을 때
- 중간에 에러가 발생했을 때 (롤백)
로직이 이상하거나 추가해야 될 부분이 있으면 말해주세요!

사용자의 플레이리스트 삭제 API 추가

---

server/src/constants.ts
server/src/entity/music.entity.ts
server/src/entity/music_playlist.entity.ts
server/src/entity/recent_played.entity.ts
server/src/music/music.controller.ts
server/src/music/music.service.ts

- #352 
- 관계에 casecade 설정을 넣어서 music 이 삭제되면 그 음악을 가지고 있는 music_playlist 와 recent_played 객체도 삭제되도록 설정했습니다.
- db 에서 해당 음악파일과 커버사진을 저장하고 있는 폴더를 삭제하도록 구현했습니다.
- 현재 object storage 에서 삭제하다가 오류가 생기면 DB 삭제 롤백은 안되어있어서 트랜잭션 추가가 필요합니다. (추가 예정)
- 테스트도 해서 작동 확인을 했는데 다시 테스트하기가 번거로워서 사진은 추가하지 않겠습니다.
실수한 부분이 있어보인다면 알려주세요!

노래 삭제 API 구현

---

android/core/domain/src/main/java/com/ohdodok/catchytape/core/domain/usecase/player/CurrentPlayListUseCase.kt
android/feature/home/src/main/java/com/ohdodok/catchytape/feature/home/HomeViewModel.kt
android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyMusicsViewModel.kt
android/feature/mypage/src/main/java/com/ohdodok/catchytape/feature/mypage/MyPageViewModel.kt
android/feature/playlist/src/main/java/com/ohdodok/catchytape/feature/playlist/PlaylistDetailViewModel.kt
android/feature/search/src/main/java/com/ohdodok/catchytape/feature/search/SearchViewModel.kt

- #349 
- CurrentPlaylistUseCase에서 CoroutineScope 제거

CurrentPlaylistUseCase 리팩토링

---

server/src/auth/auth.service.spec.ts
server/src/entity/playlist.entity.ts
server/src/playlist/playlist.module.ts
server/src/playlist/playlist.repository.ts
server/src/playlist/playlist.service.ts

- #384 
- Data Mapper 패턴으로 전환을 위해 PlaylistRepository 를 생성하고 모든 쿼리문을 옮겼습니다.
- Playlist entity 안에는 모든 쿼리문이 삭제됐습니다.
- 다만, playlist service 안에 있는 코드 중 일부는 다른 모듈과 연결되어 있어서 일부 남아있습니다.
- 변경한 함수들 모두 로컬 테스트 완료했습니다!

Playlist Repository 생성

---

.github/workflows/server-cd.yml
server/deploy.sh

- #ISSUE_NUM
* 환경변수 설정 전역으로 변경
* [수정 과정 링크](https://round-caution-9fd.notion.site/9e409f0304874583b1b4560913b23020?pvs=4)

배포 스트립트 수정

---

.github/workflows/server-cd-spring.yml
.github/workflows/server-cd.yml
server/nest/src/app.controller.spec.ts
server/nest/src/app.service.ts

- #409 
- 디렉토리 수정에 따른 배포 스크립트 수정

cd 스크립트 수정
